server:
  port: 80
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /public/**
  resources:
    add-mappings: true
  thymeleaf:
    servlet:
        content-type: text/html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dzcjd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8
#    username: root
#    password: root
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB